### ISSUE TITLE
error in test

### ISSUE THREAD

**Issue by kastoestoramadus** [anotheria/moskito-demo#10]
> mvn install
(...)
Tests in error: 
  test(org.anotheria.moskitodemo.guestbook.business.BusinessCommentCounterTest): No producer with id BusinessCommentCounter registered

Is it crucial to run demo?

**Comment by kastoestoramadus** [comment]
Does any lower Java version is needed?

**Comment by kastoestoramadus** [comment]
skipping tests with 
-Dmaven.test.skip=true
do not work

**Comment by aosadchy** [comment]
@kastoestoramadus 

Hi, it really seems to fail because of JDK 1.8. 
JDK 1.7 + Maven 3.0.5 works for me

**Comment by dvayanu** [comment]
Hi,
this demo-project is quite outdated (unfortunately), last commit 3 years ago.
If you want a working demo project:
http://blog.anotheria.net/msk/the-complete-moskito-integration-guide-step-1/

if you want to click latest ui:
http://newest.moskito.org/moskito/
